name: hd-bet

channels:
  - pytorch
  - conda-forge
  
dependencies:
  - python=3.6
  - numpy
  - ipython
  - scikit-image
  - cudatoolkit=9.2
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pip
  - pip:
    - SimpleITK
