name: hd-bet

channels:
  - pytorch
  - conda-forge
  
dependencies:
  - python=3.6
  - numpy
  - ipython
  - scikit-image
  - cudatoolkit=10.0
  - "pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0"
  - torchvision=0.4.0
  - pip
  - pip:
    - SimpleITK
